names100/names100/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^resgain/', include('resgain.urls', namespace='resgain')),
]

names100/resgain/urls.py
from django.conf.urls import url

from resgain import views

urlpatterns = [
    url(r'^index/', views.index, name='index'),
    url(r'^names/(.+)', views.names, name='names'),
    url(r'^info/(.+)', views.info, name='info'),
]

names100/resgain/models.py
from django.db import models

# Create your models here.


class Surnames(models.Model):
    """
    姓氏：
    """
    id = models.IntegerField(primary_key=True, verbose_name='id')
    surname = models.CharField(max_length=32, verbose_name='姓氏')
    nums = models.CharField(max_length=32, verbose_name='数量')

    class Meta:
        db_table = 'surnames'


class Names(models.Model):
    """
    姓名：
    """
    id = models.IntegerField(primary_key=True, verbose_name='id')
    name = models.CharField(max_length=32, verbose_name='姓名')
    surname = models.CharField(max_length=32, verbose_name='姓氏')
    nums = models.CharField(max_length=32, verbose_name='数量')
    boy_progress = models.CharField(max_length=32, verbose_name='男生比例')
    girl_progress = models.CharField(max_length=32, verbose_name='女生比例')
    total_solution = models.CharField(max_length=1024, verbose_name='总解')
    wuxing = models.CharField(max_length=32, verbose_name='五行')

    class Meta:
        db_table = 'names'

names100/resgain/views.py
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render

from resgain.models import Surnames, Names


def index(request):
    if request.method == 'GET':
        xs = Surnames.objects.all()
        xs_list = []
        list1 = []
        for item in range(len(xs)):
            list1.append(xs[item])
            if len(list1) == 7:
                xs_list.append(list1)
                list1 = []
        # print(xs_list)
        return render(request, 'index.html', {'xs_list': xs_list})


def names(request, i):
    if request.method == 'GET':
        # return render(request, 'names.html')
        names = Names.objects.filter(surname=i)
        name_list = []
        list1 = []
        for item in range(len(names)):
            list1.append(names[item])
            if len(list1) == 15:
                name_list.append(list1)
                list1 = []

        try:
            page_number = int(request.GET.get('page', 1))
        except:
            page_number = 1

        paginator = Paginator(name_list, 20)
        pages = paginator.page(page_number)

        return render(request, 'names.html', {'pages': pages, 'i': i})


def info(request, i):
    if request.method == 'GET':
        name = Names.objects.filter(name=i)
        return render(request, 'info.html', {'name': name, 'i': i})

names100/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    {% block css %}{% endblock %}

</head>
<body>

    {% block content %}{% endblock %}

    {% block js %}{% endblock %}

</body>
</html>

names100/templates/base_main.html
{% extends 'base.html' %}


{% block css %}{% endblock %}

{% block js %}{% endblock %}

{% block content %}{% endblock %}

names100/templates/index.html
{% extends 'base_main.html' %}

{% block title %}
    名字大全
{% endblock %}


{% block content %}

    <div style="background-color: aquamarine; text-align: center">
        <div style="height: 50px; width: 100%;margin-top: -50px; position: fixed; background-color: cornflowerblue" align="center">
            <input type="text" style=" margin-top: 10px; height: 45%; width: 30%" placeholder="搜索名字 ">
            <input type="button" style=" margin-top: 10px; height: 50%;" value="搜索">
        </div>
        <table align="center" style="margin-top: 50px;">
            {% for list1 in xs_list %}
                <tr>
                    {% for xs in list1 %}
                        <td style="background-color: aliceblue;">
                            <a href="{% url 'resgain:names' xs.surname %}" style="text-decoration: none; color: gray;" title="	{{ xs.surname }}姓名字大全共有{{ xs.surname }}姓名字{{ xs.nums }}个">{{ xs.surname }}姓名字大全</a>
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

names100/templates/info.html
{% extends 'base_main.html' %}


{% block title %}
    {{ i }}
{% endblock %}

{% block content %}

    <div style="background-color: white;">
        <div style="width: 40%; margin-left: 50px; margin-top: 100px;">
            <div>名字：{{ name.0.name }}</div>
            <div>人数：{{ name.0.nums }}</div>
            <div>男性名字所占比例：{{ name.0.boy_progress }}%</div>
            <div>女性名字所占比例：{{ name.0.girl_progress }}%</div>
            <div>总解：{{ name.0.total_solution }}</div>
            <div>五行：{{ name.0.wuxing }}</div>
        </div>

    </div>

{% endblock %}

names100/templates/names.html
{% extends 'base_main.html' %}

{% block title %}
    {{ i }}姓之家
{% endblock %}

{% block content %}

    <div style="background-color: aquamarine; text-align: center">
        <div style="height: 50px; width: 100%;margin-top: -50px; position: fixed; background-color: cornflowerblue" align="center">
            <input type="text" style=" margin-top: 10px; height: 45%; width: 30%" placeholder="搜索名字 ">
            <input type="button" style=" margin-top: 10px; height: 50%;" value="搜索">
        </div>
        <table align="center" style="margin-top: 50px;">
            {% for page in pages %}
                <tr>
                    {% for names in page %}
                        <td style="background-color: aliceblue;">
                            <a href="{% url 'resgain:info' names.name %}" style="text-decoration: none; color: gray;">{{ names.name }}</a>
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>
    <div style="background-color: aquamarine; text-align: center">
        <aside class="paging">
            <a>当前{{ pages.number }}页</a>
            <a style="text-decoration: none" href="{% url 'resgain:names' pages.0.0.surname %}">首页</a>

            {% for j in pages.paginator.page_range %}
                <a style="text-decoration: none; color: red;" href="{% url 'resgain:names' pages.0.0.surname %}?page={{ j }}">{{ j }}</a>
            {% endfor %}

            <a style="text-decoration: none" href="{% url 'resgain:names' pages.0.0.surname %}?page={{ page.paginator.num_pages }}">尾页</a>

        </aside>
    </div>


{% endblock %}

{% block js %}
    <script src="/static/js/names.js"></script>
{% endblock %}